### ISSUE TITLE
As a fresh Python learner , It's hard to learn TensorFlow without Data.

### ISSUE THREAD

**Issue by SSSSHIELD** [jinfagang/tensorflow_poems#12]
I cloned this Project. But there were some ERROR in this Project. It seems like I don't have any DataSets. So I readed README again. "由于数据大小的原因我没有把数据放到repo里面，大家🏠我的QQ： 1195889656 或者微信： jintianiloveu 我发给你们把，顺便给我们的项目点个赞哦！～" .I think the Author could put those in Dropbox or sth else...

**Comment by jinfagang** [comment]
For the first run, you are run from train, while checkpoints dir already have checkpoint which I haven't drop when push, this file contains my system file path, so went into file not find error, I will update to fix this. Data already in the repo.

**Comment by SSSSHIELD** [comment]
`Traceback (most recent call last):
  File "main.py", line 40, in <module>
    from inference import tang_poems
ImportError: No module named inference
`
The error occurred probably because of the lack of the following library:
`from inference import tang_poems`
`from inference import song_lyrics`

How do I solve it ? :(

**Comment by jinfagang** [comment]
You should run `python3 main.py -t poem --no-train` just inside cloned directory, tensorflow poems can find path.

**Comment by SSSSHIELD** [comment]
Same problem:
`Traceback (most recent call last):
  File "main.py", line 40, in <module>
    from inference import tang_poems
  File "/Users/Jackyy/AndroidProjects/Python/tensorflow_poems/inference/tang_poems.py", line 25, in <module>
    from dataset.poems import process_poems, generate_batch
ModuleNotFoundError: No module named 'dataset.poems'`

:(

**Comment by jinfagang** [comment]
I don't know what you did but I try to cloned my on my own fresh mechine, everything works fine. just clone and train and make poem, I can see that right result.

**Comment by SSSSHIELD** [comment]
I just solved this problem by myself.
the error caused by Can't find  following library:
`lyrics.py: from utils.clean_cn import clean_cn_corpus`
`poems.py: from utils.clean_cn import clean_cn_corpus`
And I replaced those sentence into `from tensorflow_poems.utils.clean_cn import clean_cn_corpus`.
And there a few place need to do.
Now . SHE is Training! `[INFO] Epoch: 0 , batch: 135 , training loss: 5.629035`
ThXXX..   :)

**Comment by jinfagang** [comment]
If you run `python3 main.py` just inside `tensorflow_poems/` directory this shouldn't happend. Anyway, glad to hear you successfully run it.

**Comment by SSSSHIELD** [comment]
I use PyCharm to run this Project.So I think that is the reason why I need to add `tensorflow_poems.`.

**Comment by chenjun0210** [comment]
你好，我想知道为什么python 2 就报那个找不到

**Comment by chenjun0210** [comment]
请问一下 ，为什么用python 2 就找不到对应的路径啊

**Comment by jinfagang** [comment]
Maybe not support python2, but can not find path is not about python version, you should delete checkpoints dir and train it.

**Comment by chenjun0210** [comment]
后来换成了python3 ，可以运行了，但是报这个错。Segmentation fault (core dumped)
不知道是不是gpu内存大小的原因，gpu 4G
