### ISSUE TITLE
NameError: name 'corpus_fileh' is not defined

### ISSUE THREAD

**Issue by zygmcc** [jinfagang/tensorflow_poems#27]
Traceback (most recent call last):
  File "C:\Users\root\Desktop\Pydev\githu3\tensorflow_poems-master\compose_poem.py", line 91, in <module>
## loading corpus from ./model/
    poem = gen_poem(begin_char)
  File "C:\Users\root\Desktop\Pydev\githu3\tensorflow_poems-master\compose_poem.py", line 42, in gen_poem
    poems_vector, word_int_map, vocabularies = process_poems(corpus_fileh)
NameError: name 'corpus_fileh' is not defined

That is all info.I suppose 'corpus_fileh' is a certain file?

**Comment by M-youyou** [comment]
I get the same error. How did you solve this problem?

**Comment by jinfagang** [comment]
this is actually an typo, I am so sorry about this, delete the h after corpus_file.

**Comment by M-youyou** [comment]
thanks very much, then what about  File "compose_poem.py", line 47, in gen_poem
vocabularies), rnn_size=128, num_layers=2, batch_size=64, learning_rate=FLAGS.learning_rate)
NameError: name 'FLAGS' is not defined

**Comment by zygmcc** [comment]
you can set learning_rate = 0.0001, I guess @jinfagang fogot set FLAGS  : )

**Comment by zygmcc** [comment]
but another question occurs:

Traceback (most recent call last):
  File "C:\Users\ROOT\Desktop\pyproj\tensorflow_test\tensorflow_poems-master\tensorflow_poems-master\compose_poem.py", line 91, in <module>
    poem = gen_poem(begin_char)
  File "C:\Users\ROOT\Desktop\pyproj\tensorflow_test\tensorflow_poems-master\tensorflow_poems-master\compose_poem.py", line 55, in gen_poem
    saver.restore(sess, checkpoint)
  File "C:\Users\ROOT\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1662, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by M-youyou** [comment]
I don't have this problem. The version of my tensorflow is 3.6.

**Comment by zygmcc** [comment]
@M-youyou you mean your python version ?  tensorflow only update to 1.4

**Comment by zygmcc** [comment]
my python version is 3.5.4 and tensorflow verison is 1.4

**Comment by M-youyou** [comment]
I am sorry. My python version is 3.6.1 and tensorflow version is 1.0.0.

**Comment by Liujish931** [comment]
@M-youyou yes he forgot to put FLAG , you can copy tensorflow flags from train.py to compose_poem.py 
@M-youyou  there are many tensorflow versions for different contexts , so the best solution i suggest is to retrain the model, just with python3 train.py, but i found this training very slow, not a big fan of tensorflow though ;p

**Comment by jinfagang** [comment]
Sorry guys for the mistake of typo in codes and FLAG, yes, I didn't set it. I will update codes when I am not busy.
