### ISSUE TITLE
使用的1.0版本，发现下面的错误，应该不是API的原因吧！

### ISSUE THREAD

**Issue by JiafengZhou** [jinfagang/tensorflow_poems#3]
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    tang_poems.main(True)
  File "D:\github\行人检测\tensorflow_poems-master\inference\tang_poems.py", line 141, in main
    run_training()
  File "D:\github\行人检测\tensorflow_poems-master\inference\tang_poems.py", line 87, in run_training
    saver.save(sess, os.path.join(FLAGS.checkpoints_dir, FLAGS.model_prefix), global_step=epoch)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1365, in save
    "Parent directory of {} doesn't exist, can't save.".format(save_path))
ValueError: Parent directory of D:\github\行人检测\tensorflow_poems-master\checkpoints\poems\poems doesn't exist, can't save.

**Comment by jinfagang** [comment]
Please run main.py just under project folder, to solve this mkdir under checkpoints named poems,and then run again

**Comment by iphyer** [comment]
@jinfagang @JiafengZhou  IF problems are solved, maybe you two can close it.

**Comment by jinfagang** [comment]
I close this, feel free reopen it if you still have any problem.
