### ISSUE TITLE
不明白to_word原理

### ISSUE THREAD

**Issue by retry51776** [jinfagang/tensorflow_poems#5]
我看来几遍还是不明白 to_word原理。我知道每段代码干什么，合在一起就不明白原理。我知道结果，但是不明白原理
def to_word(predict, vocabs):
    t = np.cumsum(predict)#为什么cumulative sum function？
    s = np.sum(predict)#按理说每次s都应该是差不多1，为什么还sum
    sample = int(np.searchsorted(t, np.random.rand(1) * s))#为什么generate random number，然后插入t呢？
    if sample > len(vocabs):
        sample = len(vocabs) - 1
    return vocabs[sample

**Comment by jinfagang** [comment]
This basicly means I random generated a word according to the predict vector, I can not using the most probable index because it always the ',' the dot punctuation. So this is a flexible way to get our goals.

**Comment by retry51776** [comment]
Actually s = np.sum(predict) should be s = t[-1] instead. That will reduce calculation since both should be the same value.

**Comment by retry51776** [comment]
I got way much better results with this method. Mine is a little different than yours
    def to_word(predictions):
        predictions = predictions[0]
        max_prob = max(predictions)
        #threshold = (1-max_prob)*max_prob#Generate random probility threshole
        threshold = np.random.uniform(0.4,0.7)*max_prob
        true_idx = np.argmax(predictions)
        cnt = 0
        while(True):
            idx = random.randint(0,len(predictions)-1)
            if(predictions[idx]>=threshold):
                print('cnt:',cnt,' probi:',predictions[true_idx],' true_idx:',true_idx,' w:',words[true_idx])
                print('threshold:',threshold,' pred_idx:',idx,' prob:',predictions[idx],' w:',words[idx])
                return words[idx]
            cnt += 1

**Comment by jinfagang** [comment]
Nice job, I will update your method in the next poem version

**Comment by GabrielLin** [comment]
@retry51776 I use your code but it caused an error:
Traceback (most recent call last):
  File "song_lyrics.py", line 216, in <module>
    main(False)
  File "song_lyrics.py", line 197, in main
    lyric = gen_lyric()
  File "song_lyrics.py", line 185, in gen_lyric
    word = gen_func(predict, vocabularies)
  File "song_lyrics.py", line 142, in to_word_by_retry
    return vocabs[idx]
IndexError: tuple index out of range

**Comment by 5tt2nmm** [comment]
这个工程挺有意思的，入门RNN看这个非常适合。
我提一点点粗浅的想法
之前看过这个to_word
经过softmax后出来的probs，应该是分类概率了？
我在我的代码中会把probs向量中最大概率对应那一位到字典中找对应的“word”，和CNN，BP的softmax分类后预测的方式类似。不知这样是否合理？


另外：大家都是讲中文的为何会在这里飙起英文来。

**Comment by vpegasus** [comment]
thanks for sharing this demo, it helps a lot. 
from where i stand,
to apply this function 'to_word()',  means to ignore all the effort at the stage of training, and also means there is nothing related to rnn.

**Comment by chinaos** [comment]
都是留学生么..
